name = "Meteor"
license = "MIT"
licenselink = "https://github.com/YXL76/Meteor/blob/master/LICENSE"
description = "A modern theme with a lot features."
homepage = "http://example.com/"
tags = ["Blog", "Responsive", "Google analytics", "Dark", "Light"]
features = ["search", "blog"]
min_version = "0.60.0"

[author]
  name = "YXL"
  homepage = "https://github.com/YXL76"